// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datanode.proto

#include "datanode.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace mini_storage {
PROTOBUF_CONSTEXPR WriteBlockRequest::WriteBlockRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pipeline_)*/{}
  , /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.block_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct WriteBlockRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteBlockRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteBlockRequestDefaultTypeInternal() {}
  union {
    WriteBlockRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteBlockRequestDefaultTypeInternal _WriteBlockRequest_default_instance_;
PROTOBUF_CONSTEXPR WriteBlockResponse::WriteBlockResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct WriteBlockResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WriteBlockResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WriteBlockResponseDefaultTypeInternal() {}
  union {
    WriteBlockResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WriteBlockResponseDefaultTypeInternal _WriteBlockResponse_default_instance_;
PROTOBUF_CONSTEXPR ReadBlockRequest::ReadBlockRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_id_)*/uint64_t{0u}
  , /*decltype(_impl_.offset_)*/int64_t{0}
  , /*decltype(_impl_.length_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReadBlockRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadBlockRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadBlockRequestDefaultTypeInternal() {}
  union {
    ReadBlockRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadBlockRequestDefaultTypeInternal _ReadBlockRequest_default_instance_;
PROTOBUF_CONSTEXPR ReadBlockResponse::ReadBlockResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_.crc32_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ReadBlockResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReadBlockResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReadBlockResponseDefaultTypeInternal() {}
  union {
    ReadBlockResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReadBlockResponseDefaultTypeInternal _ReadBlockResponse_default_instance_;
PROTOBUF_CONSTEXPR DeleteBlockRequest::DeleteBlockRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.block_id_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DeleteBlockRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeleteBlockRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeleteBlockRequestDefaultTypeInternal() {}
  union {
    DeleteBlockRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeleteBlockRequestDefaultTypeInternal _DeleteBlockRequest_default_instance_;
PROTOBUF_CONSTEXPR DeleteBlockResponse::DeleteBlockResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DeleteBlockResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DeleteBlockResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DeleteBlockResponseDefaultTypeInternal() {}
  union {
    DeleteBlockResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DeleteBlockResponseDefaultTypeInternal _DeleteBlockResponse_default_instance_;
PROTOBUF_CONSTEXPR DataNodeRequest::DataNodeRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.write_block_)*/nullptr
  , /*decltype(_impl_.read_block_)*/nullptr
  , /*decltype(_impl_.delete_block_)*/nullptr
  , /*decltype(_impl_.request_id_)*/uint64_t{0u}
  , /*decltype(_impl_.op_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DataNodeRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataNodeRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataNodeRequestDefaultTypeInternal() {}
  union {
    DataNodeRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataNodeRequestDefaultTypeInternal _DataNodeRequest_default_instance_;
PROTOBUF_CONSTEXPR DataNodeResponse::DataNodeResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.write_block_)*/nullptr
  , /*decltype(_impl_.read_block_)*/nullptr
  , /*decltype(_impl_.delete_block_)*/nullptr
  , /*decltype(_impl_.request_id_)*/uint64_t{0u}
  , /*decltype(_impl_.success_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct DataNodeResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataNodeResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataNodeResponseDefaultTypeInternal() {}
  union {
    DataNodeResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataNodeResponseDefaultTypeInternal _DataNodeResponse_default_instance_;
}  // namespace mini_storage
static ::_pb::Metadata file_level_metadata_datanode_2eproto[8];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_datanode_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_datanode_2eproto = nullptr;

const uint32_t TableStruct_datanode_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mini_storage::WriteBlockRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mini_storage::WriteBlockRequest, _impl_.block_id_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::WriteBlockRequest, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::WriteBlockRequest, _impl_.pipeline_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mini_storage::WriteBlockResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mini_storage::WriteBlockResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::WriteBlockResponse, _impl_.error_message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mini_storage::ReadBlockRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mini_storage::ReadBlockRequest, _impl_.block_id_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::ReadBlockRequest, _impl_.offset_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::ReadBlockRequest, _impl_.length_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mini_storage::ReadBlockResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mini_storage::ReadBlockResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::ReadBlockResponse, _impl_.data_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::ReadBlockResponse, _impl_.crc32_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::ReadBlockResponse, _impl_.error_message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mini_storage::DeleteBlockRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mini_storage::DeleteBlockRequest, _impl_.block_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mini_storage::DeleteBlockResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mini_storage::DeleteBlockResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DeleteBlockResponse, _impl_.error_message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeRequest, _impl_.op_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeRequest, _impl_.request_id_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeRequest, _impl_.write_block_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeRequest, _impl_.read_block_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeRequest, _impl_.delete_block_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeResponse, _impl_.success_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeResponse, _impl_.error_message_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeResponse, _impl_.request_id_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeResponse, _impl_.write_block_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeResponse, _impl_.read_block_),
  PROTOBUF_FIELD_OFFSET(::mini_storage::DataNodeResponse, _impl_.delete_block_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::mini_storage::WriteBlockRequest)},
  { 9, -1, -1, sizeof(::mini_storage::WriteBlockResponse)},
  { 17, -1, -1, sizeof(::mini_storage::ReadBlockRequest)},
  { 26, -1, -1, sizeof(::mini_storage::ReadBlockResponse)},
  { 36, -1, -1, sizeof(::mini_storage::DeleteBlockRequest)},
  { 43, -1, -1, sizeof(::mini_storage::DeleteBlockResponse)},
  { 51, -1, -1, sizeof(::mini_storage::DataNodeRequest)},
  { 62, -1, -1, sizeof(::mini_storage::DataNodeResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::mini_storage::_WriteBlockRequest_default_instance_._instance,
  &::mini_storage::_WriteBlockResponse_default_instance_._instance,
  &::mini_storage::_ReadBlockRequest_default_instance_._instance,
  &::mini_storage::_ReadBlockResponse_default_instance_._instance,
  &::mini_storage::_DeleteBlockRequest_default_instance_._instance,
  &::mini_storage::_DeleteBlockResponse_default_instance_._instance,
  &::mini_storage::_DataNodeRequest_default_instance_._instance,
  &::mini_storage::_DataNodeResponse_default_instance_._instance,
};

const char descriptor_table_protodef_datanode_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016datanode.proto\022\014mini_storage\"E\n\021WriteB"
  "lockRequest\022\020\n\010block_id\030\001 \001(\004\022\014\n\004data\030\002 "
  "\001(\014\022\020\n\010pipeline\030\003 \003(\t\"<\n\022WriteBlockRespo"
  "nse\022\017\n\007success\030\001 \001(\010\022\025\n\rerror_message\030\002 "
  "\001(\t\"D\n\020ReadBlockRequest\022\020\n\010block_id\030\001 \001("
  "\004\022\016\n\006offset\030\002 \001(\003\022\016\n\006length\030\003 \001(\003\"X\n\021Rea"
  "dBlockResponse\022\017\n\007success\030\001 \001(\010\022\014\n\004data\030"
  "\002 \001(\014\022\r\n\005crc32\030\003 \001(\r\022\025\n\rerror_message\030\004 "
  "\001(\t\"&\n\022DeleteBlockRequest\022\020\n\010block_id\030\001 "
  "\001(\004\"=\n\023DeleteBlockResponse\022\017\n\007success\030\001 "
  "\001(\010\022\025\n\rerror_message\030\002 \001(\t\"\266\002\n\017DataNodeR"
  "equest\0220\n\002op\030\001 \001(\0162$.mini_storage.DataNo"
  "deRequest.OpType\022\022\n\nrequest_id\030\002 \001(\004\0224\n\013"
  "write_block\030\n \001(\0132\037.mini_storage.WriteBl"
  "ockRequest\0222\n\nread_block\030\013 \001(\0132\036.mini_st"
  "orage.ReadBlockRequest\0226\n\014delete_block\030\014"
  " \001(\0132 .mini_storage.DeleteBlockRequest\";"
  "\n\006OpType\022\017\n\013WRITE_BLOCK\020\000\022\016\n\nREAD_BLOCK\020"
  "\001\022\020\n\014DELETE_BLOCK\020\002\"\363\001\n\020DataNodeResponse"
  "\022\017\n\007success\030\001 \001(\010\022\025\n\rerror_message\030\002 \001(\t"
  "\022\022\n\nrequest_id\030\003 \001(\004\0225\n\013write_block\030\n \001("
  "\0132 .mini_storage.WriteBlockResponse\0223\n\nr"
  "ead_block\030\013 \001(\0132\037.mini_storage.ReadBlock"
  "Response\0227\n\014delete_block\030\014 \001(\0132!.mini_st"
  "orage.DeleteBlockResponseb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_datanode_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_datanode_2eproto = {
    false, false, 993, descriptor_table_protodef_datanode_2eproto,
    "datanode.proto",
    &descriptor_table_datanode_2eproto_once, nullptr, 0, 8,
    schemas, file_default_instances, TableStruct_datanode_2eproto::offsets,
    file_level_metadata_datanode_2eproto, file_level_enum_descriptors_datanode_2eproto,
    file_level_service_descriptors_datanode_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_datanode_2eproto_getter() {
  return &descriptor_table_datanode_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_datanode_2eproto(&descriptor_table_datanode_2eproto);
namespace mini_storage {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DataNodeRequest_OpType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_datanode_2eproto);
  return file_level_enum_descriptors_datanode_2eproto[0];
}
bool DataNodeRequest_OpType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr DataNodeRequest_OpType DataNodeRequest::WRITE_BLOCK;
constexpr DataNodeRequest_OpType DataNodeRequest::READ_BLOCK;
constexpr DataNodeRequest_OpType DataNodeRequest::DELETE_BLOCK;
constexpr DataNodeRequest_OpType DataNodeRequest::OpType_MIN;
constexpr DataNodeRequest_OpType DataNodeRequest::OpType_MAX;
constexpr int DataNodeRequest::OpType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class WriteBlockRequest::_Internal {
 public:
};

WriteBlockRequest::WriteBlockRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mini_storage.WriteBlockRequest)
}
WriteBlockRequest::WriteBlockRequest(const WriteBlockRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WriteBlockRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pipeline_){from._impl_.pipeline_}
    , decltype(_impl_.data_){}
    , decltype(_impl_.block_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.block_id_ = from._impl_.block_id_;
  // @@protoc_insertion_point(copy_constructor:mini_storage.WriteBlockRequest)
}

inline void WriteBlockRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pipeline_){arena}
    , decltype(_impl_.data_){}
    , decltype(_impl_.block_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

WriteBlockRequest::~WriteBlockRequest() {
  // @@protoc_insertion_point(destructor:mini_storage.WriteBlockRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WriteBlockRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.pipeline_.~RepeatedPtrField();
  _impl_.data_.Destroy();
}

void WriteBlockRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WriteBlockRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mini_storage.WriteBlockRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pipeline_.Clear();
  _impl_.data_.ClearToEmpty();
  _impl_.block_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WriteBlockRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 block_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.block_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated string pipeline = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_pipeline();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "mini_storage.WriteBlockRequest.pipeline"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WriteBlockRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mini_storage.WriteBlockRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 block_id = 1;
  if (this->_internal_block_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_block_id(), target);
  }

  // bytes data = 2;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_data(), target);
  }

  // repeated string pipeline = 3;
  for (int i = 0, n = this->_internal_pipeline_size(); i < n; i++) {
    const auto& s = this->_internal_pipeline(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mini_storage.WriteBlockRequest.pipeline");
    target = stream->WriteString(3, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mini_storage.WriteBlockRequest)
  return target;
}

size_t WriteBlockRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mini_storage.WriteBlockRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string pipeline = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.pipeline_.size());
  for (int i = 0, n = _impl_.pipeline_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.pipeline_.Get(i));
  }

  // bytes data = 2;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // uint64 block_id = 1;
  if (this->_internal_block_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_block_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WriteBlockRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WriteBlockRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WriteBlockRequest::GetClassData() const { return &_class_data_; }


void WriteBlockRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WriteBlockRequest*>(&to_msg);
  auto& from = static_cast<const WriteBlockRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mini_storage.WriteBlockRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.pipeline_.MergeFrom(from._impl_.pipeline_);
  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (from._internal_block_id() != 0) {
    _this->_internal_set_block_id(from._internal_block_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WriteBlockRequest::CopyFrom(const WriteBlockRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mini_storage.WriteBlockRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WriteBlockRequest::IsInitialized() const {
  return true;
}

void WriteBlockRequest::InternalSwap(WriteBlockRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.pipeline_.InternalSwap(&other->_impl_.pipeline_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  swap(_impl_.block_id_, other->_impl_.block_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata WriteBlockRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[0]);
}

// ===================================================================

class WriteBlockResponse::_Internal {
 public:
};

WriteBlockResponse::WriteBlockResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mini_storage.WriteBlockResponse)
}
WriteBlockResponse::WriteBlockResponse(const WriteBlockResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  WriteBlockResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.success_ = from._impl_.success_;
  // @@protoc_insertion_point(copy_constructor:mini_storage.WriteBlockResponse)
}

inline void WriteBlockResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

WriteBlockResponse::~WriteBlockResponse() {
  // @@protoc_insertion_point(destructor:mini_storage.WriteBlockResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WriteBlockResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_message_.Destroy();
}

void WriteBlockResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WriteBlockResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mini_storage.WriteBlockResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* WriteBlockResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error_message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mini_storage.WriteBlockResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WriteBlockResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mini_storage.WriteBlockResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mini_storage.WriteBlockResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mini_storage.WriteBlockResponse)
  return target;
}

size_t WriteBlockResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mini_storage.WriteBlockResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData WriteBlockResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    WriteBlockResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*WriteBlockResponse::GetClassData() const { return &_class_data_; }


void WriteBlockResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<WriteBlockResponse*>(&to_msg);
  auto& from = static_cast<const WriteBlockResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mini_storage.WriteBlockResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void WriteBlockResponse::CopyFrom(const WriteBlockResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mini_storage.WriteBlockResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WriteBlockResponse::IsInitialized() const {
  return true;
}

void WriteBlockResponse::InternalSwap(WriteBlockResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  swap(_impl_.success_, other->_impl_.success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata WriteBlockResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[1]);
}

// ===================================================================

class ReadBlockRequest::_Internal {
 public:
};

ReadBlockRequest::ReadBlockRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mini_storage.ReadBlockRequest)
}
ReadBlockRequest::ReadBlockRequest(const ReadBlockRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReadBlockRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_id_){}
    , decltype(_impl_.offset_){}
    , decltype(_impl_.length_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.block_id_, &from._impl_.block_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.length_) -
    reinterpret_cast<char*>(&_impl_.block_id_)) + sizeof(_impl_.length_));
  // @@protoc_insertion_point(copy_constructor:mini_storage.ReadBlockRequest)
}

inline void ReadBlockRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_id_){uint64_t{0u}}
    , decltype(_impl_.offset_){int64_t{0}}
    , decltype(_impl_.length_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ReadBlockRequest::~ReadBlockRequest() {
  // @@protoc_insertion_point(destructor:mini_storage.ReadBlockRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReadBlockRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ReadBlockRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReadBlockRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mini_storage.ReadBlockRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.block_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.length_) -
      reinterpret_cast<char*>(&_impl_.block_id_)) + sizeof(_impl_.length_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReadBlockRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 block_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.block_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 offset = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int64 length = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReadBlockRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mini_storage.ReadBlockRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 block_id = 1;
  if (this->_internal_block_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_block_id(), target);
  }

  // int64 offset = 2;
  if (this->_internal_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(2, this->_internal_offset(), target);
  }

  // int64 length = 3;
  if (this->_internal_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_length(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mini_storage.ReadBlockRequest)
  return target;
}

size_t ReadBlockRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mini_storage.ReadBlockRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 block_id = 1;
  if (this->_internal_block_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_block_id());
  }

  // int64 offset = 2;
  if (this->_internal_offset() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_offset());
  }

  // int64 length = 3;
  if (this->_internal_length() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_length());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadBlockRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReadBlockRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadBlockRequest::GetClassData() const { return &_class_data_; }


void ReadBlockRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReadBlockRequest*>(&to_msg);
  auto& from = static_cast<const ReadBlockRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mini_storage.ReadBlockRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_block_id() != 0) {
    _this->_internal_set_block_id(from._internal_block_id());
  }
  if (from._internal_offset() != 0) {
    _this->_internal_set_offset(from._internal_offset());
  }
  if (from._internal_length() != 0) {
    _this->_internal_set_length(from._internal_length());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReadBlockRequest::CopyFrom(const ReadBlockRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mini_storage.ReadBlockRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadBlockRequest::IsInitialized() const {
  return true;
}

void ReadBlockRequest::InternalSwap(ReadBlockRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReadBlockRequest, _impl_.length_)
      + sizeof(ReadBlockRequest::_impl_.length_)
      - PROTOBUF_FIELD_OFFSET(ReadBlockRequest, _impl_.block_id_)>(
          reinterpret_cast<char*>(&_impl_.block_id_),
          reinterpret_cast<char*>(&other->_impl_.block_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReadBlockRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[2]);
}

// ===================================================================

class ReadBlockResponse::_Internal {
 public:
};

ReadBlockResponse::ReadBlockResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mini_storage.ReadBlockResponse)
}
ReadBlockResponse::ReadBlockResponse(const ReadBlockResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ReadBlockResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.success_){}
    , decltype(_impl_.crc32_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_data().empty()) {
    _this->_impl_.data_.Set(from._internal_data(), 
      _this->GetArenaForAllocation());
  }
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.success_, &from._impl_.success_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.crc32_) -
    reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.crc32_));
  // @@protoc_insertion_point(copy_constructor:mini_storage.ReadBlockResponse)
}

inline void ReadBlockResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){}
    , decltype(_impl_.error_message_){}
    , decltype(_impl_.success_){false}
    , decltype(_impl_.crc32_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.data_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.data_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ReadBlockResponse::~ReadBlockResponse() {
  // @@protoc_insertion_point(destructor:mini_storage.ReadBlockResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReadBlockResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.Destroy();
  _impl_.error_message_.Destroy();
}

void ReadBlockResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ReadBlockResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mini_storage.ReadBlockResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.ClearToEmpty();
  _impl_.error_message_.ClearToEmpty();
  ::memset(&_impl_.success_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.crc32_) -
      reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.crc32_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReadBlockResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_data();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 crc32 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.crc32_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error_message = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mini_storage.ReadBlockResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReadBlockResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mini_storage.ReadBlockResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // bytes data = 2;
  if (!this->_internal_data().empty()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_data(), target);
  }

  // uint32 crc32 = 3;
  if (this->_internal_crc32() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_crc32(), target);
  }

  // string error_message = 4;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mini_storage.ReadBlockResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mini_storage.ReadBlockResponse)
  return target;
}

size_t ReadBlockResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mini_storage.ReadBlockResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes data = 2;
  if (!this->_internal_data().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_data());
  }

  // string error_message = 4;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  // uint32 crc32 = 3;
  if (this->_internal_crc32() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_crc32());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReadBlockResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ReadBlockResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReadBlockResponse::GetClassData() const { return &_class_data_; }


void ReadBlockResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ReadBlockResponse*>(&to_msg);
  auto& from = static_cast<const ReadBlockResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mini_storage.ReadBlockResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_data().empty()) {
    _this->_internal_set_data(from._internal_data());
  }
  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  if (from._internal_crc32() != 0) {
    _this->_internal_set_crc32(from._internal_crc32());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReadBlockResponse::CopyFrom(const ReadBlockResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mini_storage.ReadBlockResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReadBlockResponse::IsInitialized() const {
  return true;
}

void ReadBlockResponse::InternalSwap(ReadBlockResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.data_, lhs_arena,
      &other->_impl_.data_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ReadBlockResponse, _impl_.crc32_)
      + sizeof(ReadBlockResponse::_impl_.crc32_)
      - PROTOBUF_FIELD_OFFSET(ReadBlockResponse, _impl_.success_)>(
          reinterpret_cast<char*>(&_impl_.success_),
          reinterpret_cast<char*>(&other->_impl_.success_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ReadBlockResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[3]);
}

// ===================================================================

class DeleteBlockRequest::_Internal {
 public:
};

DeleteBlockRequest::DeleteBlockRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mini_storage.DeleteBlockRequest)
}
DeleteBlockRequest::DeleteBlockRequest(const DeleteBlockRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DeleteBlockRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.block_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.block_id_ = from._impl_.block_id_;
  // @@protoc_insertion_point(copy_constructor:mini_storage.DeleteBlockRequest)
}

inline void DeleteBlockRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.block_id_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DeleteBlockRequest::~DeleteBlockRequest() {
  // @@protoc_insertion_point(destructor:mini_storage.DeleteBlockRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DeleteBlockRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void DeleteBlockRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DeleteBlockRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mini_storage.DeleteBlockRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.block_id_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DeleteBlockRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 block_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.block_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DeleteBlockRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mini_storage.DeleteBlockRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 block_id = 1;
  if (this->_internal_block_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_block_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mini_storage.DeleteBlockRequest)
  return target;
}

size_t DeleteBlockRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mini_storage.DeleteBlockRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint64 block_id = 1;
  if (this->_internal_block_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_block_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DeleteBlockRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DeleteBlockRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DeleteBlockRequest::GetClassData() const { return &_class_data_; }


void DeleteBlockRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DeleteBlockRequest*>(&to_msg);
  auto& from = static_cast<const DeleteBlockRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mini_storage.DeleteBlockRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_block_id() != 0) {
    _this->_internal_set_block_id(from._internal_block_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DeleteBlockRequest::CopyFrom(const DeleteBlockRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mini_storage.DeleteBlockRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeleteBlockRequest::IsInitialized() const {
  return true;
}

void DeleteBlockRequest::InternalSwap(DeleteBlockRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.block_id_, other->_impl_.block_id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DeleteBlockRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[4]);
}

// ===================================================================

class DeleteBlockResponse::_Internal {
 public:
};

DeleteBlockResponse::DeleteBlockResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mini_storage.DeleteBlockResponse)
}
DeleteBlockResponse::DeleteBlockResponse(const DeleteBlockResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DeleteBlockResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.success_ = from._impl_.success_;
  // @@protoc_insertion_point(copy_constructor:mini_storage.DeleteBlockResponse)
}

inline void DeleteBlockResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DeleteBlockResponse::~DeleteBlockResponse() {
  // @@protoc_insertion_point(destructor:mini_storage.DeleteBlockResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DeleteBlockResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_message_.Destroy();
}

void DeleteBlockResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DeleteBlockResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mini_storage.DeleteBlockResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  _impl_.success_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DeleteBlockResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error_message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mini_storage.DeleteBlockResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DeleteBlockResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mini_storage.DeleteBlockResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mini_storage.DeleteBlockResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mini_storage.DeleteBlockResponse)
  return target;
}

size_t DeleteBlockResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mini_storage.DeleteBlockResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DeleteBlockResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DeleteBlockResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DeleteBlockResponse::GetClassData() const { return &_class_data_; }


void DeleteBlockResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DeleteBlockResponse*>(&to_msg);
  auto& from = static_cast<const DeleteBlockResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mini_storage.DeleteBlockResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DeleteBlockResponse::CopyFrom(const DeleteBlockResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mini_storage.DeleteBlockResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DeleteBlockResponse::IsInitialized() const {
  return true;
}

void DeleteBlockResponse::InternalSwap(DeleteBlockResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  swap(_impl_.success_, other->_impl_.success_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DeleteBlockResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[5]);
}

// ===================================================================

class DataNodeRequest::_Internal {
 public:
  static const ::mini_storage::WriteBlockRequest& write_block(const DataNodeRequest* msg);
  static const ::mini_storage::ReadBlockRequest& read_block(const DataNodeRequest* msg);
  static const ::mini_storage::DeleteBlockRequest& delete_block(const DataNodeRequest* msg);
};

const ::mini_storage::WriteBlockRequest&
DataNodeRequest::_Internal::write_block(const DataNodeRequest* msg) {
  return *msg->_impl_.write_block_;
}
const ::mini_storage::ReadBlockRequest&
DataNodeRequest::_Internal::read_block(const DataNodeRequest* msg) {
  return *msg->_impl_.read_block_;
}
const ::mini_storage::DeleteBlockRequest&
DataNodeRequest::_Internal::delete_block(const DataNodeRequest* msg) {
  return *msg->_impl_.delete_block_;
}
DataNodeRequest::DataNodeRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mini_storage.DataNodeRequest)
}
DataNodeRequest::DataNodeRequest(const DataNodeRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DataNodeRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.write_block_){nullptr}
    , decltype(_impl_.read_block_){nullptr}
    , decltype(_impl_.delete_block_){nullptr}
    , decltype(_impl_.request_id_){}
    , decltype(_impl_.op_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_write_block()) {
    _this->_impl_.write_block_ = new ::mini_storage::WriteBlockRequest(*from._impl_.write_block_);
  }
  if (from._internal_has_read_block()) {
    _this->_impl_.read_block_ = new ::mini_storage::ReadBlockRequest(*from._impl_.read_block_);
  }
  if (from._internal_has_delete_block()) {
    _this->_impl_.delete_block_ = new ::mini_storage::DeleteBlockRequest(*from._impl_.delete_block_);
  }
  ::memcpy(&_impl_.request_id_, &from._impl_.request_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.op_) -
    reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.op_));
  // @@protoc_insertion_point(copy_constructor:mini_storage.DataNodeRequest)
}

inline void DataNodeRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.write_block_){nullptr}
    , decltype(_impl_.read_block_){nullptr}
    , decltype(_impl_.delete_block_){nullptr}
    , decltype(_impl_.request_id_){uint64_t{0u}}
    , decltype(_impl_.op_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

DataNodeRequest::~DataNodeRequest() {
  // @@protoc_insertion_point(destructor:mini_storage.DataNodeRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DataNodeRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.write_block_;
  if (this != internal_default_instance()) delete _impl_.read_block_;
  if (this != internal_default_instance()) delete _impl_.delete_block_;
}

void DataNodeRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DataNodeRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:mini_storage.DataNodeRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.write_block_ != nullptr) {
    delete _impl_.write_block_;
  }
  _impl_.write_block_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.read_block_ != nullptr) {
    delete _impl_.read_block_;
  }
  _impl_.read_block_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.delete_block_ != nullptr) {
    delete _impl_.delete_block_;
  }
  _impl_.delete_block_ = nullptr;
  ::memset(&_impl_.request_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.op_) -
      reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.op_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DataNodeRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .mini_storage.DataNodeRequest.OpType op = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_op(static_cast<::mini_storage::DataNodeRequest_OpType>(val));
        } else
          goto handle_unusual;
        continue;
      // uint64 request_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .mini_storage.WriteBlockRequest write_block = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_write_block(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .mini_storage.ReadBlockRequest read_block = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_read_block(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .mini_storage.DeleteBlockRequest delete_block = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_delete_block(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DataNodeRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mini_storage.DataNodeRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .mini_storage.DataNodeRequest.OpType op = 1;
  if (this->_internal_op() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_op(), target);
  }

  // uint64 request_id = 2;
  if (this->_internal_request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(2, this->_internal_request_id(), target);
  }

  // .mini_storage.WriteBlockRequest write_block = 10;
  if (this->_internal_has_write_block()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::write_block(this),
        _Internal::write_block(this).GetCachedSize(), target, stream);
  }

  // .mini_storage.ReadBlockRequest read_block = 11;
  if (this->_internal_has_read_block()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, _Internal::read_block(this),
        _Internal::read_block(this).GetCachedSize(), target, stream);
  }

  // .mini_storage.DeleteBlockRequest delete_block = 12;
  if (this->_internal_has_delete_block()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(12, _Internal::delete_block(this),
        _Internal::delete_block(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mini_storage.DataNodeRequest)
  return target;
}

size_t DataNodeRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mini_storage.DataNodeRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .mini_storage.WriteBlockRequest write_block = 10;
  if (this->_internal_has_write_block()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.write_block_);
  }

  // .mini_storage.ReadBlockRequest read_block = 11;
  if (this->_internal_has_read_block()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.read_block_);
  }

  // .mini_storage.DeleteBlockRequest delete_block = 12;
  if (this->_internal_has_delete_block()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.delete_block_);
  }

  // uint64 request_id = 2;
  if (this->_internal_request_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_request_id());
  }

  // .mini_storage.DataNodeRequest.OpType op = 1;
  if (this->_internal_op() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_op());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DataNodeRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DataNodeRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DataNodeRequest::GetClassData() const { return &_class_data_; }


void DataNodeRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DataNodeRequest*>(&to_msg);
  auto& from = static_cast<const DataNodeRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mini_storage.DataNodeRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_write_block()) {
    _this->_internal_mutable_write_block()->::mini_storage::WriteBlockRequest::MergeFrom(
        from._internal_write_block());
  }
  if (from._internal_has_read_block()) {
    _this->_internal_mutable_read_block()->::mini_storage::ReadBlockRequest::MergeFrom(
        from._internal_read_block());
  }
  if (from._internal_has_delete_block()) {
    _this->_internal_mutable_delete_block()->::mini_storage::DeleteBlockRequest::MergeFrom(
        from._internal_delete_block());
  }
  if (from._internal_request_id() != 0) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  if (from._internal_op() != 0) {
    _this->_internal_set_op(from._internal_op());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DataNodeRequest::CopyFrom(const DataNodeRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mini_storage.DataNodeRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataNodeRequest::IsInitialized() const {
  return true;
}

void DataNodeRequest::InternalSwap(DataNodeRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DataNodeRequest, _impl_.op_)
      + sizeof(DataNodeRequest::_impl_.op_)
      - PROTOBUF_FIELD_OFFSET(DataNodeRequest, _impl_.write_block_)>(
          reinterpret_cast<char*>(&_impl_.write_block_),
          reinterpret_cast<char*>(&other->_impl_.write_block_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DataNodeRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[6]);
}

// ===================================================================

class DataNodeResponse::_Internal {
 public:
  static const ::mini_storage::WriteBlockResponse& write_block(const DataNodeResponse* msg);
  static const ::mini_storage::ReadBlockResponse& read_block(const DataNodeResponse* msg);
  static const ::mini_storage::DeleteBlockResponse& delete_block(const DataNodeResponse* msg);
};

const ::mini_storage::WriteBlockResponse&
DataNodeResponse::_Internal::write_block(const DataNodeResponse* msg) {
  return *msg->_impl_.write_block_;
}
const ::mini_storage::ReadBlockResponse&
DataNodeResponse::_Internal::read_block(const DataNodeResponse* msg) {
  return *msg->_impl_.read_block_;
}
const ::mini_storage::DeleteBlockResponse&
DataNodeResponse::_Internal::delete_block(const DataNodeResponse* msg) {
  return *msg->_impl_.delete_block_;
}
DataNodeResponse::DataNodeResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:mini_storage.DataNodeResponse)
}
DataNodeResponse::DataNodeResponse(const DataNodeResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DataNodeResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.write_block_){nullptr}
    , decltype(_impl_.read_block_){nullptr}
    , decltype(_impl_.delete_block_){nullptr}
    , decltype(_impl_.request_id_){}
    , decltype(_impl_.success_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_error_message().empty()) {
    _this->_impl_.error_message_.Set(from._internal_error_message(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_write_block()) {
    _this->_impl_.write_block_ = new ::mini_storage::WriteBlockResponse(*from._impl_.write_block_);
  }
  if (from._internal_has_read_block()) {
    _this->_impl_.read_block_ = new ::mini_storage::ReadBlockResponse(*from._impl_.read_block_);
  }
  if (from._internal_has_delete_block()) {
    _this->_impl_.delete_block_ = new ::mini_storage::DeleteBlockResponse(*from._impl_.delete_block_);
  }
  ::memcpy(&_impl_.request_id_, &from._impl_.request_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.success_) -
    reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.success_));
  // @@protoc_insertion_point(copy_constructor:mini_storage.DataNodeResponse)
}

inline void DataNodeResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_message_){}
    , decltype(_impl_.write_block_){nullptr}
    , decltype(_impl_.read_block_){nullptr}
    , decltype(_impl_.delete_block_){nullptr}
    , decltype(_impl_.request_id_){uint64_t{0u}}
    , decltype(_impl_.success_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.error_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.error_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DataNodeResponse::~DataNodeResponse() {
  // @@protoc_insertion_point(destructor:mini_storage.DataNodeResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DataNodeResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.error_message_.Destroy();
  if (this != internal_default_instance()) delete _impl_.write_block_;
  if (this != internal_default_instance()) delete _impl_.read_block_;
  if (this != internal_default_instance()) delete _impl_.delete_block_;
}

void DataNodeResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DataNodeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:mini_storage.DataNodeResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_message_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.write_block_ != nullptr) {
    delete _impl_.write_block_;
  }
  _impl_.write_block_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.read_block_ != nullptr) {
    delete _impl_.read_block_;
  }
  _impl_.read_block_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.delete_block_ != nullptr) {
    delete _impl_.delete_block_;
  }
  _impl_.delete_block_ = nullptr;
  ::memset(&_impl_.request_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.request_id_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DataNodeResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool success = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.success_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string error_message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_error_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "mini_storage.DataNodeResponse.error_message"));
        } else
          goto handle_unusual;
        continue;
      // uint64 request_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.request_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .mini_storage.WriteBlockResponse write_block = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_write_block(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .mini_storage.ReadBlockResponse read_block = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_read_block(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .mini_storage.DeleteBlockResponse delete_block = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_delete_block(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DataNodeResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:mini_storage.DataNodeResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool success = 1;
  if (this->_internal_success() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_success(), target);
  }

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_error_message().data(), static_cast<int>(this->_internal_error_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "mini_storage.DataNodeResponse.error_message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_error_message(), target);
  }

  // uint64 request_id = 3;
  if (this->_internal_request_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_request_id(), target);
  }

  // .mini_storage.WriteBlockResponse write_block = 10;
  if (this->_internal_has_write_block()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::write_block(this),
        _Internal::write_block(this).GetCachedSize(), target, stream);
  }

  // .mini_storage.ReadBlockResponse read_block = 11;
  if (this->_internal_has_read_block()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, _Internal::read_block(this),
        _Internal::read_block(this).GetCachedSize(), target, stream);
  }

  // .mini_storage.DeleteBlockResponse delete_block = 12;
  if (this->_internal_has_delete_block()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(12, _Internal::delete_block(this),
        _Internal::delete_block(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:mini_storage.DataNodeResponse)
  return target;
}

size_t DataNodeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:mini_storage.DataNodeResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string error_message = 2;
  if (!this->_internal_error_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_error_message());
  }

  // .mini_storage.WriteBlockResponse write_block = 10;
  if (this->_internal_has_write_block()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.write_block_);
  }

  // .mini_storage.ReadBlockResponse read_block = 11;
  if (this->_internal_has_read_block()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.read_block_);
  }

  // .mini_storage.DeleteBlockResponse delete_block = 12;
  if (this->_internal_has_delete_block()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.delete_block_);
  }

  // uint64 request_id = 3;
  if (this->_internal_request_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_request_id());
  }

  // bool success = 1;
  if (this->_internal_success() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DataNodeResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DataNodeResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DataNodeResponse::GetClassData() const { return &_class_data_; }


void DataNodeResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DataNodeResponse*>(&to_msg);
  auto& from = static_cast<const DataNodeResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:mini_storage.DataNodeResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error_message().empty()) {
    _this->_internal_set_error_message(from._internal_error_message());
  }
  if (from._internal_has_write_block()) {
    _this->_internal_mutable_write_block()->::mini_storage::WriteBlockResponse::MergeFrom(
        from._internal_write_block());
  }
  if (from._internal_has_read_block()) {
    _this->_internal_mutable_read_block()->::mini_storage::ReadBlockResponse::MergeFrom(
        from._internal_read_block());
  }
  if (from._internal_has_delete_block()) {
    _this->_internal_mutable_delete_block()->::mini_storage::DeleteBlockResponse::MergeFrom(
        from._internal_delete_block());
  }
  if (from._internal_request_id() != 0) {
    _this->_internal_set_request_id(from._internal_request_id());
  }
  if (from._internal_success() != 0) {
    _this->_internal_set_success(from._internal_success());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DataNodeResponse::CopyFrom(const DataNodeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:mini_storage.DataNodeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataNodeResponse::IsInitialized() const {
  return true;
}

void DataNodeResponse::InternalSwap(DataNodeResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.error_message_, lhs_arena,
      &other->_impl_.error_message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DataNodeResponse, _impl_.success_)
      + sizeof(DataNodeResponse::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(DataNodeResponse, _impl_.write_block_)>(
          reinterpret_cast<char*>(&_impl_.write_block_),
          reinterpret_cast<char*>(&other->_impl_.write_block_));
}

::PROTOBUF_NAMESPACE_ID::Metadata DataNodeResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_datanode_2eproto_getter, &descriptor_table_datanode_2eproto_once,
      file_level_metadata_datanode_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace mini_storage
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::mini_storage::WriteBlockRequest*
Arena::CreateMaybeMessage< ::mini_storage::WriteBlockRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mini_storage::WriteBlockRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mini_storage::WriteBlockResponse*
Arena::CreateMaybeMessage< ::mini_storage::WriteBlockResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mini_storage::WriteBlockResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::mini_storage::ReadBlockRequest*
Arena::CreateMaybeMessage< ::mini_storage::ReadBlockRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mini_storage::ReadBlockRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mini_storage::ReadBlockResponse*
Arena::CreateMaybeMessage< ::mini_storage::ReadBlockResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mini_storage::ReadBlockResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::mini_storage::DeleteBlockRequest*
Arena::CreateMaybeMessage< ::mini_storage::DeleteBlockRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mini_storage::DeleteBlockRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mini_storage::DeleteBlockResponse*
Arena::CreateMaybeMessage< ::mini_storage::DeleteBlockResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mini_storage::DeleteBlockResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::mini_storage::DataNodeRequest*
Arena::CreateMaybeMessage< ::mini_storage::DataNodeRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mini_storage::DataNodeRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::mini_storage::DataNodeResponse*
Arena::CreateMaybeMessage< ::mini_storage::DataNodeResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::mini_storage::DataNodeResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
